Adicionada implementação de pesquisa dinâmica e dependência do Mockito
utfprapps-pb/idr-api pull request #5
Opened 2024-04-23 00:32 UTC by andreytondo

Documentação completa: [ClickUp](https://app.clickup.com/t/86dt9mybh)

2024-04-23 01:38 UTC, Minozzzi approved these changes
Ficou muito boa sua lógica, não conheço muito de Java mas para mim parece bem organizado e estruturado!

2024-04-23 01:38 UTC, Minozzzi commented on src/main/java/br/edu/utfpr/ProjetoIDRAPI/specexecutor/DiseaaseSpecExecutor.java
> +public interface DiseaaseSpecExecutor extends JpaSpecificationExecutor<Disease> {
Era para ser `Diseaase` o nome da interface e do file?

2024-04-23 19:06 UTC, viniciuspegorini commented on src/main/java/br/edu/utfpr/ProjetoIDRAPI/specexecutor/DiseaaseSpecExecutor.java
> +public interface DiseaaseSpecExecutor extends JpaSpecificationExecutor<Disease> {
Tem um erro Typo em Deseaase, sobrou um "a"

2024-04-23 19:07 UTC, viniciuspegorini commented on src/main/java/br/edu/utfpr/ProjetoIDRAPI/repository/DiseaseRepository.java
Ajustar o nome do  DiseaaseSpecExecutor para  DiseaseSpecExecutor

2024-04-23 19:08 UTC, viniciuspegorini commented on src/main/java/br/edu/utfpr/ProjetoIDRAPI/specexecutor/DiseaaseSpecExecutor.java
DiseaaseSpecExecutor para  DiseaseSpecExecutor

2024-04-23 19:09 UTC, viniciuspegorini requested changes
Ficou bem bom, apenas ajustar o nome da interface  DiseaaseSpecExecutor.

2024-04-27 22:36 UTC, andreytondo commented
Ajuste realizado

2024-04-28 01:14 UTC, viniciuspegorini approved these changes
Ok.

2024-04-30 00:42 UTC, merged